// import localFont from "next/font/local";
import "@a/globals.css";
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'], // 필요한 문자 집합 설정
  display: 'swap', // 폰트 로딩 방식 설정
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// ${geistSans.variable} ${geistMono.variable}
export const metadata = {
  title: "next하자",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body
        className={`${inter.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
