
import "@a/globals.css";
import { Inter } from 'next/font/google';
import { Sidebar } from "@a/components/Sidebar";


const inter = Inter({
  subsets: ['latin'], // 필요한 문자 집합 설정
  display: 'swap', // 폰트 로딩 방식 설정
});

export const metadata = {
  title: "next하자",
  description: "Generated by create next app",
};

export default function AdmLayout({ children }) {
  return (
    <html lang="ko">
      <body
        className={`${inter.className} antialiased`}
      >
        <div className="flex">
          <div className="h-[100vh]">
            <Sidebar></Sidebar>
          </div>

          <div className={`flex-1`}>
            {children}
          </div>
        </div>

      </body>
    </html>
  );
}
